// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHhwDgkrug8Temg6WnYFjt1JZGDxWEsu0',
    appId: '1:189918028915:web:d8b5bc8f812bfb1f273606',
    messagingSenderId: '189918028915',
    projectId: 'realneersreports',
    authDomain: 'realneersreports.firebaseapp.com',
    storageBucket: 'realneersreports.firebasestorage.app',
    measurementId: 'G-G5T5K4VB9Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC74VOdQIrXlAahxMX8j3oge8Xz8um6f2s',
    appId: '1:189918028915:android:1ac637c21563f834273606',
    messagingSenderId: '189918028915',
    projectId: 'realneersreports',
    storageBucket: 'realneersreports.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAIUlLYXML7fcjBhLVN00ntZEj7N8KNg2s',
    appId: '1:189918028915:ios:5d48bedc357b8fcc273606',
    messagingSenderId: '189918028915',
    projectId: 'realneersreports',
    storageBucket: 'realneersreports.firebasestorage.app',
    iosBundleId: 'pro.devpaul.realneersReports',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAIUlLYXML7fcjBhLVN00ntZEj7N8KNg2s',
    appId: '1:189918028915:ios:5d48bedc357b8fcc273606',
    messagingSenderId: '189918028915',
    projectId: 'realneersreports',
    storageBucket: 'realneersreports.firebasestorage.app',
    iosBundleId: 'pro.devpaul.realneersReports',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAHhwDgkrug8Temg6WnYFjt1JZGDxWEsu0',
    appId: '1:189918028915:web:e0763b413ae0f00b273606',
    messagingSenderId: '189918028915',
    projectId: 'realneersreports',
    authDomain: 'realneersreports.firebaseapp.com',
    storageBucket: 'realneersreports.firebasestorage.app',
    measurementId: 'G-SVG9RLRKRG',
  );
}
